#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v13
# autospec commit: dc0ff31
#
Name     : lldpd
Version  : 1.0.18
Release  : 6
URL      : https://github.com/lldpd/lldpd/releases/download/1.0.18/lldpd-1.0.18.tar.gz
Source0  : https://github.com/lldpd/lldpd/releases/download/1.0.18/lldpd-1.0.18.tar.gz
Summary  : libevent_extra
Group    : Development/Tools
License  : BSD-3-Clause ISC MIT
Requires: lldpd-autostart = %{version}-%{release}
Requires: lldpd-bin = %{version}-%{release}
Requires: lldpd-config = %{version}-%{release}
Requires: lldpd-data = %{version}-%{release}
Requires: lldpd-lib = %{version}-%{release}
Requires: lldpd-license = %{version}-%{release}
Requires: lldpd-man = %{version}-%{release}
Requires: lldpd-services = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : doxygen
BuildRequires : libxml2-dev
BuildRequires : perl
BuildRequires : pkgconfig(check)
BuildRequires : pkgconfig(libbsd-overlay)
BuildRequires : pkgconfig(zlib)
BuildRequires : sed
BuildRequires : valgrind
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# lldpd: implementation of IEEE 802.1ab (LLDP)
![Build Status](https://github.com/lldpd/lldpd/workflows/CI/badge.svg)

%package autostart
Summary: autostart components for the lldpd package.
Group: Default

%description autostart
autostart components for the lldpd package.


%package bin
Summary: bin components for the lldpd package.
Group: Binaries
Requires: lldpd-data = %{version}-%{release}
Requires: lldpd-config = %{version}-%{release}
Requires: lldpd-license = %{version}-%{release}
Requires: lldpd-services = %{version}-%{release}

%description bin
bin components for the lldpd package.


%package config
Summary: config components for the lldpd package.
Group: Default

%description config
config components for the lldpd package.


%package data
Summary: data components for the lldpd package.
Group: Data

%description data
data components for the lldpd package.


%package dev
Summary: dev components for the lldpd package.
Group: Development
Requires: lldpd-lib = %{version}-%{release}
Requires: lldpd-bin = %{version}-%{release}
Requires: lldpd-data = %{version}-%{release}
Provides: lldpd-devel = %{version}-%{release}
Requires: lldpd = %{version}-%{release}

%description dev
dev components for the lldpd package.


%package doc
Summary: doc components for the lldpd package.
Group: Documentation
Requires: lldpd-man = %{version}-%{release}

%description doc
doc components for the lldpd package.


%package lib
Summary: lib components for the lldpd package.
Group: Libraries
Requires: lldpd-data = %{version}-%{release}
Requires: lldpd-license = %{version}-%{release}

%description lib
lib components for the lldpd package.


%package license
Summary: license components for the lldpd package.
Group: Default

%description license
license components for the lldpd package.


%package man
Summary: man components for the lldpd package.
Group: Default

%description man
man components for the lldpd package.


%package services
Summary: services components for the lldpd package.
Group: Systemd services
Requires: systemd

%description services
services components for the lldpd package.


%prep
%setup -q -n lldpd-1.0.18
cd %{_builddir}/lldpd-1.0.18
pushd ..
cp -a lldpd-1.0.18 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1719973399
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static --with-systemdsystemunitdir=/usr/lib/systemd/system \
--with-sysusersdir=/usr/lib/sysusers.d
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static --with-systemdsystemunitdir=/usr/lib/systemd/system \
--with-sysusersdir=/usr/lib/sysusers.d
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1719973399
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/lldpd
cp %{_builddir}/lldpd-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/lldpd/a6a67dc7ee17afcdbf108fb5a0465a6244809d49 || :
cp %{_builddir}/lldpd-%{version}/libevent/LICENSE %{buildroot}/usr/share/package-licenses/lldpd/0f375374b877550ade2e001905a1f9c9b7128714 || :
cp %{_builddir}/lldpd-%{version}/libevent/cmake/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/lldpd/cc31ae51223e291f3f7389a4c96b2cf4c1e62757 || :
cp %{_builddir}/lldpd-%{version}/libevent/cmake/Copyright.txt %{buildroot}/usr/share/package-licenses/lldpd/b7708e46727dc00ced77b6421d1f4b4e4045c12d || :
cp %{_builddir}/lldpd-%{version}/osx/resources/license.html %{buildroot}/usr/share/package-licenses/lldpd/f35e6410a2fea0a868cb057d72d3c04fcc730ef1 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
## install_append content
mkdir -p %{buildroot}/usr/lib/systemd/system/multi-user.target.wants/
ln -s ../lldpd.service %{buildroot}/usr/lib/systemd/system/multi-user.target.wants/lldpd.service
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files autostart
%defattr(-,root,root,-)
/usr/lib/systemd/system/multi-user.target.wants/lldpd.service

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/lldpcli
/V3/usr/bin/lldpd
/usr/bin/lldpcli
/usr/bin/lldpctl
/usr/bin/lldpd

%files config
%defattr(-,root,root,-)
/usr/lib/sysusers.d/lldpd.sysusers.conf

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/lldpcli
/usr/share/zsh/site-functions/_lldpcli

%files dev
%defattr(-,root,root,-)
/usr/include/lldp-const.h
/usr/include/lldpctl.h
/usr/lib64/liblldpctl.so
/usr/lib64/pkgconfig/lldpctl.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/lldpd/*

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/liblldpctl.so.4.9.1
/usr/lib64/liblldpctl.so.4
/usr/lib64/liblldpctl.so.4.9.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/lldpd/0f375374b877550ade2e001905a1f9c9b7128714
/usr/share/package-licenses/lldpd/a6a67dc7ee17afcdbf108fb5a0465a6244809d49
/usr/share/package-licenses/lldpd/b7708e46727dc00ced77b6421d1f4b4e4045c12d
/usr/share/package-licenses/lldpd/cc31ae51223e291f3f7389a4c96b2cf4c1e62757
/usr/share/package-licenses/lldpd/f35e6410a2fea0a868cb057d72d3c04fcc730ef1

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/lldpcli.8
/usr/share/man/man8/lldpctl.8
/usr/share/man/man8/lldpd.8

%files services
%defattr(-,root,root,-)
%exclude /usr/lib/systemd/system/multi-user.target.wants/lldpd.service
/usr/lib/systemd/system/lldpd.service
