#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
Name     : lldpd
Version  : 1.0.16
Release  : 1
URL      : https://github.com/lldpd/lldpd/releases/download/1.0.16/lldpd-1.0.16.tar.gz
Source0  : https://github.com/lldpd/lldpd/releases/download/1.0.16/lldpd-1.0.16.tar.gz
Summary  : libevent_pthreads adds pthreads-based threading support to libevent
Group    : Development/Tools
License  : BSD-3-Clause ISC MIT
Requires: lldpd-bin = %{version}-%{release}
Requires: lldpd-data = %{version}-%{release}
Requires: lldpd-lib = %{version}-%{release}
Requires: lldpd-license = %{version}-%{release}
Requires: lldpd-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : doxygen
BuildRequires : libcap-dev
BuildRequires : libxml2-dev
BuildRequires : perl
BuildRequires : pkgconfig(check)
BuildRequires : pkgconfig(libbsd-overlay)
BuildRequires : pkgconfig(zlib)
BuildRequires : sed
BuildRequires : valgrind
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# lldpd: implementation of IEEE 802.1ab (LLDP)
![Build Status](https://github.com/lldpd/lldpd/workflows/CI/badge.svg)

%package bin
Summary: bin components for the lldpd package.
Group: Binaries
Requires: lldpd-data = %{version}-%{release}
Requires: lldpd-license = %{version}-%{release}

%description bin
bin components for the lldpd package.


%package data
Summary: data components for the lldpd package.
Group: Data

%description data
data components for the lldpd package.


%package dev
Summary: dev components for the lldpd package.
Group: Development
Requires: lldpd-lib = %{version}-%{release}
Requires: lldpd-bin = %{version}-%{release}
Requires: lldpd-data = %{version}-%{release}
Provides: lldpd-devel = %{version}-%{release}
Requires: lldpd = %{version}-%{release}

%description dev
dev components for the lldpd package.


%package doc
Summary: doc components for the lldpd package.
Group: Documentation
Requires: lldpd-man = %{version}-%{release}

%description doc
doc components for the lldpd package.


%package lib
Summary: lib components for the lldpd package.
Group: Libraries
Requires: lldpd-data = %{version}-%{release}
Requires: lldpd-license = %{version}-%{release}

%description lib
lib components for the lldpd package.


%package license
Summary: license components for the lldpd package.
Group: Default

%description license
license components for the lldpd package.


%package man
Summary: man components for the lldpd package.
Group: Default

%description man
man components for the lldpd package.


%prep
%setup -q -n lldpd-1.0.16
cd %{_builddir}/lldpd-1.0.16

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1682701885
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1682701885
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/lldpd
cp %{_builddir}/lldpd-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/lldpd/a6a67dc7ee17afcdbf108fb5a0465a6244809d49 || :
cp %{_builddir}/lldpd-%{version}/libevent/LICENSE %{buildroot}/usr/share/package-licenses/lldpd/0f375374b877550ade2e001905a1f9c9b7128714 || :
cp %{_builddir}/lldpd-%{version}/libevent/cmake/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/lldpd/cc31ae51223e291f3f7389a4c96b2cf4c1e62757 || :
cp %{_builddir}/lldpd-%{version}/libevent/cmake/Copyright.txt %{buildroot}/usr/share/package-licenses/lldpd/b7708e46727dc00ced77b6421d1f4b4e4045c12d || :
cp %{_builddir}/lldpd-%{version}/osx/resources/license.html %{buildroot}/usr/share/package-licenses/lldpd/f35e6410a2fea0a868cb057d72d3c04fcc730ef1 || :
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/lldpcli
/usr/bin/lldpctl
/usr/bin/lldpd

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/lldpcli
/usr/share/zsh/site-functions/_lldpcli

%files dev
%defattr(-,root,root,-)
/usr/include/lldp-const.h
/usr/include/lldpctl.h
/usr/lib64/liblldpctl.so
/usr/lib64/pkgconfig/lldpctl.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/lldpd/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/liblldpctl.so.4
/usr/lib64/liblldpctl.so.4.9.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/lldpd/0f375374b877550ade2e001905a1f9c9b7128714
/usr/share/package-licenses/lldpd/a6a67dc7ee17afcdbf108fb5a0465a6244809d49
/usr/share/package-licenses/lldpd/b7708e46727dc00ced77b6421d1f4b4e4045c12d
/usr/share/package-licenses/lldpd/cc31ae51223e291f3f7389a4c96b2cf4c1e62757
/usr/share/package-licenses/lldpd/f35e6410a2fea0a868cb057d72d3c04fcc730ef1

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/lldpcli.8
/usr/share/man/man8/lldpctl.8
/usr/share/man/man8/lldpd.8
